### ISSUE TITLE
Question about the code of md_nvt_lj.f90 

### ISSUE THREAD

**Issue by Stephen2252** [Allen-Tildesley/examples#11]
In the row 123, column 31,of the code file md_nvt_lj.f90,  the number of dim is 2. But I think it should be equal to 1. I am not sure. 
The detailed content is as the folling picture describes:
![_20181105140606](https://user-images.githubusercontent.com/40737041/47980814-49dae080-e104-11e8-9e94-e340e8ed33b8.png)

**Comment by Michael-P-Allen** [comment]
Hi there! Thank you for your interest in the example codes, and for raising this issue. 

However, in this case, you are mistaken: the code is correct. The velocity array `v` is of rank 2, and is declared in the file `md_lj_module.f90` to have the shape `(3,n)`.  In the `sum` function, the optional argument `dim=2` indicates that the sum is to be performed over the 2nd index of the array; the result is an array of rank 1, having 3 elements. After dividing by `n`, this array corresponds to the _x_, _y_, and _z_ components of the centre-of-mass velocity. In the following statement, this array is duplicated (spread) `n` times, again using the `dim=2` argument to specify the shape of the resulting rank-2 array, which is again `(3,n)`. This can be subtracted from the original velocity array.

I hope that's clear: please let me know if you still have any concerns. Otherwise, I'll close this issue.

**Comment by Stephen2252** [comment]
Your answer is very clear, thank you.

**Comment by Michael-P-Allen** [comment]
OK, good, I'll close this issue now.
