### ISSUE TITLE
is there a mistake about the np.real ?

### ISSUE THREAD

**Issue by connor-circle** [Allen-Tildesley/examples#12]
Hi professor ,
in my mentioned link , the line 137 ,the np.real is used to get the real part of the complex ,but in your book ,P498 ,there is "where Im(z) is the imaginary part of a complex number".
is there some wrong with that?
https://github.com/Allen-Tildesley/examples/blob/94be209763167a52233de6b3b9143255da5d13f8/python_examples/ewald_module.py#L137

**Comment by Michael-P-Allen** [comment]
Thanks for your interest in the Python examples. In this case, the argument of the `np.real` function will have zero imaginary part, because `term` is multiplied by its complex conjugate. So, the function is simply discarding this zero imaginary part, and providing a real quantity for the remainder of the calculation. Does this answer your question? If not, please can you clarify your question, because I don't see where the problem lies.

**Comment by connor-circle** [comment]
it was  my mistake. the code is used to calculate potential .I got it wrong (i mixed the potential formula with force formula).
and i have another three  questions.
![IMG_0687](https://user-images.githubusercontent.com/35033310/56567424-779adf80-65e7-11e9-9c38-45d07f8bb3dd.jpg)
in the potential formula, there is 0.5,and in the force formula,the 0.5 is gone, but I do not get rid of 0.5 after the derivative.
and the second term in the potential formula has 2Π/V ,but from the chapter6,there should be 1/(2V).
and the third term in the potential formula has a plus sign ,but i think it should minus sign.

**Comment by Michael-P-Allen** [comment]
I am going to close this issue, as it seems that there is no problem with this example. This is not the right place to ask questions about the book. We maintain a separate [corrections page](https://github.com/Allen-Tildesley/corrections) for that. Please, however, recheck your algebra first. If you believe that you have found a mistake, please give the full details there. It may take a day or two before I can respond.
