### ISSUE TITLE
Compiling failure using scons

### ISSUE THREAD

**Issue by Alan-Rusty24** [Allen-Tildesley/examples#5]
I'm using ubuntu 16.04 with fftw, blas, lapack installed. However, I'm failing to compile the program even after adding the correct path to the libraries in SConstruct file.

Please let me know what I might be doing wrong. I did the following changes to the SConstruct file to provide proper path to the fftw and lapack libraries.

FFTW_F90FLAGS='-fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -I/usr/include'
LAPACK_LINKFLAGS='-L/usr/lib/ -llapack'
FFTW_LINKFLAGS='-L/usr/lib/x86-64-linux-gnu/ -lfftw3'

[errors.txt](https://github.com/Allen-Tildesley/examples/files/1218444/errors.txt)

I'm attaching the error.txt file that has the last few lines that were printed on screen including the compilation error, when it failed to build.

**Comment by Allen-Tildesley** [comment]
As we say in the README, we cannot offer specific advice on building the codes. This is because there are so many different computer systems, and in general your system is not the same as ours. I'll keep this issue open for a short while in case you manage to solve the problem, but then I'll have to close it, as it does not seem to be an issue with the computer codes themselves. I can only offer very general advice. Are you able to compile a simple LAPACK example code (e.g. from their website) from the command line? This should sort out the issue of paths. If you can do that, can you compile the md_chain_mts_lj example yourself, from the command line? If so, how does the command line differ from the one that appears in the error.txt file?

**Comment by Alan-Rusty24** [comment]
Hello again

Thanks for your general advice and suggestions.

So based on your suggestions, i tried compiling a simple lapack test program and it does complie and run. No issues there.

Based on that example i found out that -llapack is used after the objects and not before, so i tried compiling 

gfortran -o build_md_chain_mts_lj/md_chain_mts_lj build_md_chain_mts_lj/md_chain_mts_lj.o build_md_chain_mts_lj/md_chain_lj_module.o build_md_chain_mts_lj/config_io_module.o build_md_chain_mts_lj/averages_module.o -llapack

instead of what SConstruct is doing, that is

gfortran -o build_md_chain_mts_lj/md_chain_mts_lj -llapack build_md_chain_mts_lj/md_chain_mts_lj.o build_md_chain_mts_lj/md_chain_lj_module.o build_md_chain_mts_lj/config_io_module.o build_md_chain_mts_lj/averages_module.o

It looks like linking the library works when it is linked in the end after the objects and not before. I don't know why?

Is there a way I can modify your SConstruct such that it compiles all the program by putting -llapack in the end and not in the beginning?

**Comment by Alan-Rusty24** [comment]
Have found a workaround but it's not elegant.

I've commented the lines in SConstruct file that needs compiling with lapack or fftw by searching for env_fftw and env_lapack. then ran 

scons

Compiled the remaining codes manually one by one as per the method above by including -llapack or -lfftw in the end after the objects and not before. 

Please pardon my ignorance of the scons method because I've never used it before using it for compiling these codes. It looks like a common error of linking -lfftw or -llapack flag before the objects and it seems to fail but somehow it works if I include it after the objects.

This is version of gfortran
GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by Allen-Tildesley** [comment]
Thanks for this information, very helpful. It looks like I should be using the LIBS variable, not the LINKFLAGS variable, to specify the actual library in each case. Makes no difference on my system, but may be essential on yours, and presumably others. Attached here is a possible replacement SConstruct file. I've uploaded it as SConstruct.txt. After comparing it with your current SConstruct file and changing the paths again to suit your system, please could you change its name to SConstruct and try the build process again?

Edit: On further thought, I should also be using the LIBPATH variable to specify the search path for libraries, rather than putting the information in LINKFLAGS. The attached file should include this change too.

[SConstruct.txt](https://github.com/Allen-Tildesley/examples/files/1219545/SConstruct.txt)

**Comment by Alan-Rusty24** [comment]
Works!!

I just modified three lines to include correct path for my corresponding libraries

FFTW_F90FLAGS='-fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -I/usr/include'
LAPACK_LIBPATH='/usr/lib'
FFTW_LIBPATH='/usr/lib/x86-64-linux-gnu'

The issue seems resolved.

Thanks again.

**Comment by Allen-Tildesley** [comment]
Thanks for raising this issue, and resolving it. I've reopened it briefly because I have just committed a modified SConstruct file which includes the fix, and is also somewhat tidied up. I'd be grateful if you could download that file, modify it for your system, and confirm that it works. If it's OK, you can close the issue once more. Thanks again.

**Comment by Alan-Rusty24** [comment]
It compiled without any issues.
