### ISSUE TITLE
Revise mc_nvt_poly_lj

### ISSUE THREAD

**Issue by Allen-Tildesley** [Allen-Tildesley/examples#8]
This example would probably benefit from adding a Python version. At the same time we could do some tidying up: calculating atomic positions outside the potential routines might be an improvement.

**Comment by Michael-P-Allen** [comment]
Reviewing the Fortran version has revealed a bug in the random_rotate_quaternion routine, within maths_module.f90 (which only affects this example). As well as fixing this, I shall take a look at adding a smoothing term to the potential, instead of just shifting it, to make it match the one described in the reference Mossa et al (2002).
